# SQL Basic Select
<p>The following practice problems were completed on <a href="www.hackerrank.com">HackerRank.com</a>.</p>
<p>Generally speaking, the problems ascend from easier to more difficult.</p>
<p>Relational Database Management System: <b>MySQL</b></p>

## Problem Set Table #1

The CITY table is described as follows:
<img src='images/1449729804-f21d187d0f-CITY.jpg'>

### Problems
1. Select All: Query all columns (attributes) for every row in the CITY table. (Difficulty: <span style='color:green'>Easy</span>)
2. Select By ID: Query all columns for a city in CITY with the ID 1661. (Difficulty: <span style='color:green'>Easy</span>)
3. Japanese Cities' Attributes: Query all attributes of every Japanese city in the CITY table. The COUNTRYCODE for Japan is JPN. (Difficulty: <span style='color:green'>Easy</span>)
4. Japanese Cities' Names: Query the names of all the Japanese cities in the CITY table. The COUNTRYCODE for Japan is JPN. (Difficulty: <span style='color:green'>Easy</span>)

#### Query #1
Select All: Query all columns (attributes) for every row in the CITY table. (Difficulty: <span style='color:green'>Easy</span>)
##### Query
SELECT *  
FROM CITY;
##### Output
6 Rotterdam NLD Zuid-Holland 593321  
3878 Scottsdale USA Arizona 202705  
3965 Corona USA California 124966  
3973 Concord USA California 121780  
3977 Cedar Rapids USA Iowa 120758  
3982 Coral Springs USA Florida 117549  
4054 Fairfield USA California 92256  
4058 Boulder USA Colorado 91238  
4061 Fall River USA Massachusetts 90555

#### Query #2
Select By ID: Query all columns for a city in CITY with the ID 1661. (Difficulty: <span style='color:green'>Easy</span>)
##### Query
SELECT *  
FROM CITY  
WHERE ID = 1661;
##### Output
1661 Sayama JPN Saitama 162472

#### Query #3
Japanese Cities' Attributes: Query all attributes of every Japanese city in the CITY table. The COUNTRYCODE for Japan is JPN. (Difficulty: <span style='color:green'>Easy</span>)
##### Query
SELECT *  
FROM CITY  
WHERE COUNTRYCODE = 'JPN';
##### Output
1613 Neyagawa JPN Osaka 257315  
1630 Ageo JPN Saitama 209442  
1661 Sayama JPN Saitama 162472  
1681 Omuta JPN Fukuoka 142889  
1739 Tokuyama JPN Yamaguchi 107078

#### Query #4
Japanese Cities' Names: Query the names of all the Japanese cities in the CITY table. The COUNTRYCODE for Japan is JPN. (Difficulty: <span style='color:green'>Easy</span>)
##### Query
SELECT NAME  
FROM CITY  
WHERE COUNTRYCODE = 'JPN';
##### Output
Neyagawa  
Ageo  
Sayama  
Omuta  
Tokuyama

## Problem Set Table #2

The STATION table is described as follows:
<img src='images/1449345840-5f0a551030-Station.jpg'>
where LAT_N is the northern latitude and LONG_W is the western longitude.

### Problems
1. Weather Observation Station 1: Query a list of CITY and STATE from the STATION table. (Difficulty: <span style='color:green'>Easy</span>)
2. Weather Observation Station 3: Query a list of CITY names from STATION with even ID numbers only. You may print the results in any order, but must exclude duplicates from your answer. (Difficulty: <span style='color:green'>Easy</span>)
3. Weather Observation Station 4: Let N be the number of CITY entries in STATION, and let N' be the number of distinct CITY names in STATION; query the value of N - N' from STATION. In other words, find the difference between the total number of CITY entries in the table and the number of distinct CITY entries in the table. (Difficulty: <span style='color:green'>Easy</span>)
4. Weather Observation Station 5: Query the two cities in STATION with the shortest and longest CITY names, as well as their respective lengths (i.e.: number of characters in the name). If there is more than one smallest or largest city, choose the one that comes first when ordered alphabetically. Note: You can write two separate queries to get the desired output. It need not be a single query. (Difficulty: <span style='color:green'>Easy</span>)
5. Weather Observation Station 6: Query the list of CITY names starting with vowels (i.e., a, e, i, o, or u) from STATION. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
6. Weather Observation Station 7: Query the list of CITY names ending with vowels (a, e, i, o, u) from STATION. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
7. Weather Observation Station 8: Query the list of CITY names from STATION which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
8. Weather Observation Station 9: Query the list of CITY names from STATION that do not start with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
9. Weather Observation Station 10: Query the list of CITY names from STATION that do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
10. Weather Observation Station 11: Query the list of CITY names from STATION that either do not start with vowels or do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
11. Weather Observation Station 12: Query the list of CITY names from STATION that do not start with vowels and do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)

#### Query #1
Weather Observation Station 1: Query a list of CITY and STATE from the STATION table. (Difficulty: <span style='color:green'>Easy</span>)
##### Query
SELECT CITY, STATE  
FROM STATION;
##### Output
Acme LA  
Addison MI  
Agency MO  
Aguanga CA  
Alanson MI  
Alba MI  
Albany CA  
Albion IN  
Algonac MI  
Aliso Viejo CA  
Allerton IA  
Alpine AR  
Alton MO  
Amazonia MO  
Amo IN  
Andersonville GA  
Andover CT  
Anthony KS  
Archie MO  
Arispe IA {-truncated-}

#### Query #2 
Weather Observation Station 3: Query a list of CITY names from STATION with even ID numbers only. You may print the results in any order, but must exclude duplicates from your answer. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE (ID % 2) = 0; 
##### Output 
Kissee Mills  
Loma Mar  
Tipton  
Glencoe  
Chignik Lagoon  
Albany  
Manchester  
Cahone  
Bowdon  
Watkins  
Millville  
Aguanga  
Morenci  
Mccomb  
Gustine  
Delano  
Roy  
Pattonsburg  
Centertown  
Norvell  
Raymondville  
West Hills  
Wickliffe  
Forest Lakes  
Little Rock  
Hampden  
Pine City  
Prince Frederick  
Yazoo City  
Jolon  
Childs  
Shreveport  
Forest  
Sizerock  
Onaway  
Hackleburg  
Bentonville  
Kirkland  
Grosse Pointe  
Busby  
Robertsdale  
Hayfork  
Mcbrides  
Henderson  
Palm Desert  
Benedict  
Oakfield  
Chokio  
Clancy  
Norwood  
Elkton  
Cherry  
Regina  
Pine Bluff  
East Irvine  
Pony  
Franklin  
Amo  
Vulcan  
Prairie Du Rocher  
Delta  
Carver  
Paron  
Greenview  
Cromwell  
Round Pond  
Rockton  
Pheba  
North Berwick  
Oconee  
Grandville  
Richland  
Philipsburg  
Frankfort Heights  
Bono  
Biggsville  
Newton Center  
Crane Lake  
Kismet  
Grayslake  
Bison  
Bellevue  
South Britain  
Rydal  
Lynnville  
Hope  
Andersonville  
Crouseville  
Ledyard  
Eros  
Rantoul  
Glen Carbon  
Mc Henry  
Howard Lake  
Salem  
Sturdivant  
East Haddam  
Eastlake  
Larkspur  
Tarzana  
Grapevine  
Kanorado  
Climax  
Curdsville  
Southport  
Compton  
Rumsey  
Rogers  
Pleasant Grove  
Everton  
Skanee  
Church Creek  
Yellow Pine  
Dumont  
Gales Ferry  
Decatur  
Holbrook  
Sherrill  
Brownsdale  
Peachtree City  
Rocheport  
Clovis  
Heyburn  
Marion Junction  
Randall  
White Horse Beach  
Macy  
Deep River  
Napoleon  
Leavenworth  
Turners Falls  
Delray Beach  
Eustis  
Mineral Point  
Bayville  
North Monmouth  
Harmony  
Beaufort  
Firebrick  
Pico Rivera  
Ludington  
West Baden Springs  
Melber  
Bainbridge  
Ottertail  
Montrose  
Schleswig  
Ermine  
Siler  
Lismore  
Athens  
Eufaula  
Hanscom Afb  
Mosca  
Bennington  
Lottie  
Garland  
Clutier  
Lupton  
Daleville  
Osage City  
Norris  
Saint Paul  
Kirksville  
Bridgton  
Brownstown  
Grand Terrace  
Mesick  
Dryden  
Marine On Saint Croix  
Hayneville  
Cheswold  
Cannonsburg  
Elm Grove  
Atlantic Mine  
Farmington  
Winter Park  
Monroe  
Greens Fork  
Garden City  
New Ross  
Archie  
Norphlet  
Keyes  
Neon  
Calhoun  
Mullan  
Walnut  
Saint Petersburg  
Julian  
Orange Park  
Ludlow  
Palatka  
Ukiah  
Yuma  
Alba  
Zachary  
Montgomery City  
Magnolia  
Dundee  
Baker  
Kenner  
Many  
Seward  
Chilhowee  
Cobalt  
South Haven  
Eskridge  
West Hyannisport  
Ozona  
Healdsburg  
Ravenden Springs  
Kell  
Strasburg  
Five Points  
Norris City  
Coaling  
Orange City  
Effingham  
Greenway  
Shingletown  
Clio  
Yalaha  
Leakesville  
Fort Lupton  
Canton  
Taft  
Knobel  
Bullhead City  
Haverhill  
Middleboro  
Lee  
Mid Florida  
Gorham  
Bass Harbor

#### Query #3
Weather Observation Station 4: Let N be the number of CITY entries in STATION, and let N' be the number of distinct CITY names in STATION; query the value of N - N' from STATION. In other words, find the difference between the total number of CITY entries in the table and the number of distinct CITY entries in the table. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)  
FROM STATION;  
##### Output 
13

#### Query #4
Weather Observation Station 5: Query the two cities in STATION with the shortest and longest CITY names, as well as their respective lengths (i.e.: number of characters in the name). If there is more than one smallest or largest city, choose the one that comes first when ordered alphabetically. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT CITY, LENGTH(CITY) AS CCC  
FROM STATION  
ORDER BY CCC ASC, CITY ASC  
LIMIT 1;  
  
SELECT CITY, LENGTH(CITY) AS CCC  
FROM STATION  
ORDER BY CCC DESC, CITY DESC  
LIMIT 1;  
##### Output 
Amo 3  
Marine On Saint Croix 21

#### Query #5
Weather Observation Station 6: Query the list of CITY names starting with vowels (i.e., a, e, i, o, or u) from STATION. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '^[AEIOUaeiou]';  
##### Output 
Arlington  
Albany  
Upperco  
Aguanga  
Odin  
East China  
Algonac  
Onaway  
Irvington  
Arrowsmith  
Udall  
Oakfield  
Elkton  
East Irvine  
Amo  
Alanson  
Eleele  
Auburn  
Oconee  
Amazonia  
Aliso Viejo  
Andersonville  
Eros  
Arkadelphia  
Eriline  
Edgewater  
East Haddam  
Eastlake  
Addison  
Everton  
Eustis  
Arispe  
Union Star  
Ottertail  
Ermine  
Albion  
Athens  
Eufaula  
Osage City  
Andover  
Osborne  
Elm Grove  
Atlantic Mine  
Oshtemo  
Archie  
Olmitz  
Allerton  
Equality  
Alpine  
Ojai  
Orange Park  
Urbana  
Ukiah  
Alba  
Esmond  
Eureka Springs  
Eskridge  
Ozona  
Orange City  
Effingham  
Alton  
Agency  
Anthony  
Emmett  
Acme

#### Query #6
Weather Observation Station 7: Query the list of CITY names ending with vowels (a, e, i, o, u) from STATION. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '[AEIOUaeiou]$';  
##### Output 
Glencoe  
Chelsea  
Pelahatchie  
Dorrance  
Cahone  
Upperco  
Waipahu  
Millville  
Aguanga  
Morenci  
South El Monte  
Gustine  
Delano  
Westphalia  
Saint Elmo  
Raymondville  
Barrigada  
Hesperia  
Wickliffe  
Milledgeville  
East China  
Gretna  
Zionsville  
Rio Oso  
Samantha  
Bentonville  
Grosse Pointe  
Robertsdale  
Dale  
Tennessee  
Chokio  
Bertha  
Regina  
Mascotte  
Netawaka  
East Irvine  
Amo  
Delta  
Jerome  
Baton Rouge  
Clarkdale  
Pheba  
Eleele  
Oconee  
Grandville  
Susanville  
Rosie  
Verona  
De Tour Village  
West Grove  
Bono  
Biggsville  
Amazonia  
Marysville  
Cape Girardeau  
Crane Lake  
Grayslake  
Bellevue  
Lynnville  
Hope  
Aliso Viejo  
Gowrie  
Andersonville  
Crouseville  
Arkadelphia  
Eriline  
Howard Lake  
Hagatna  
Eastlake  
Corriganville  
Tarzana  
Grapevine  
Kanorado  
Curdsville  
Notasulga  
Pleasant Grove  
Skanee  
Springerville  
Yellow Pine  
Ravenna  
Brownsdale  
Hayesville  
Greenville  
Yellville  
Weldona  
Cascade  
Bayville  
Arispe  
Baileyville  
Lakeville  
Pico Rivera  
Pawnee  
Bainbridge  
Dupo  
Montrose  
Ermine  
Casco  
Madisonville  
Lismore  
Eufaula  
Wildie  
Mosca  
Lottie  
Daleville  
Cuba  
Renville  
Kirksville  
Lydia  
Monona  
Lakota  
Grand Terrace  
Fort Meade  
Hayneville  
Losantville  
Caseville  
Pomona  
Hopkinsville  
Dixie  
Hillside  
Osborne  
Elm Grove  
Atlantic Mine  
Honolulu  
Oshtemo  
Monroe  
Archie  
Alpine  
Ojai  
Urbana  
Palatka  
Yuma  
Alba  
Waresboro  
Magnolia  
Dundee  
Chilhowee  
Eskridge  
Ozona  
Woodsboro  
Clio  
Yalaha  
Leakesville  
Shasta  
Calpine  
Tina  
Middleboro  
Lena  
Lee  
Mid Florida  
Acme

#### Query #7
Weather Observation Station 8: Query the list of CITY names from STATION which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '^[AEIOUaeiou].*[AEIOUaeiou]$'  
##### Output 
Upperco  
Aguanga  
East China  
East Irvine  
Amo  
Eleele  
Oconee  
Amazonia  
Aliso Viejo  
Andersonville  
Arkadelphia  
Eriline  
Eastlake  
Arispe  
Ermine  
Eufaula  
Osborne  
Elm Grove  
Atlantic Mine  
Oshtemo  
Archie  
Alpine  
Ojai  
Urbana  
Alba  
Eskridge  
Ozona  
Acme

#### Query #8
Weather Observation Station 9: Query the list of CITY names from STATION that do not start with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '^[^AEIOUaeiou]';  
##### Output 
Kissee Mills  
Loma Mar  
Sandy Hook  
Tipton  
Turner  
Slidell  
Negreet  
Glencoe  
Chelsea  
Chignik Lagoon  
Pelahatchie  
Hanna City  
Dorrance  
Monument  
Manchester  
Prescott  
Graettinger  
Cahone  
Sturgis  
Highwood  
Waipahu  
Bowdon  
Tyler  
Watkins  
Republic  
Millville  
Bowdon Junction  
Morenci  
South El Monte  
Hoskinston  
Talbert  
Mccomb  
Kirk  
Carlock  
Seward  
Gustine  
Delano  
Westphalia  
Saint Elmo  
Roy  
Pattonsburg  
Centertown  
Norvell  
Raymondville  
Beaver Island  
Jemison  
West Hills  
Barrigada  
Hesperia  
Wickliffe  
Culdesac  
Roselawn  
Forest Lakes  
San Simeon  
Little Rock  
Portland  
New Century  
Hampden  
Pine City  
Sandborn  
Seaton  
Milledgeville  
Prince Frederick  
Pomona Park  
Gretna  
Yazoo City  
Zionsville  
Rio Oso  
Jolon  
Childs  
Shreveport  
Forest  
Sizerock  
Buffalo Creek  
Winsted  
Woodbury  
Samantha  
Hackleburg  
Soldier  
Columbus  
Bentonville  
Kirkland  
Grosse Pointe  
Wilton  
Busby  
Robertsdale  
Dale  
Reeds  
Hayfork  
Mcbrides  
Lee Center  
Tennessee  
Henderson  
Palm Desert  
Benedict  
Tamms  
Haubstadt  
Chokio  
Clancy  
Scotts Valley  
Norwood  
Bertha  
Bridgeport  
Cherry  
Regina  
Griffin  
Pine Bluff  
Mascotte  
Baldwin  
Netawaka  
Pony  
Franklin  
Vulcan  
Prairie Du Rocher  
Delta  
Carver  
Paron  
Winchester  
Jerome  
Baton Rouge  
Greenview  
Lucerne Valley  
Cromwell  
Quinter  
Whitewater  
Round Pond  
Clarkdale  
Rockton  
Pheba  
North Berwick  
Grandville  
Susanville  
Rosie  
Verona  
Richland  
Fremont  
Philipsburg  
Kensett  
De Tour Village  
Koleen  
Winslow  
Reasnor  
West Grove  
Frankfort Heights  
Bono  
Biggsville  
Linthicum Heights  
Marysville  
Cape Girardeau  
Pengilly  
Newton Center  
Crane Lake  
Newbury  
Kismet  
Canton  
Clipper Mills  
Grayslake  
Pierre Part  
Bison  
Bellevue  
Ridgway  
South Britain  
Rydal  
Lynnville  
Deerfield  
Montreal  
Hope  
Gowrie  
Knob Lick  
Crouseville  
Cranks  
Rives Junction  
Ledyard  
Norway  
Rantoul  
Richmond Hill  
Fredericktown  
Glen Carbon  
Fredericksburg  
Mc Henry  
Wellington  
Hoffman Estates  
Howard Lake  
Ducor  
Salem  
Sturdivant  
Hagatna  
Larkspur  
Patriot  
Corriganville  
Carlos  
Tarzana  
Grapevine  
Kanorado  
Climax  
Curdsville  
Southport  
Compton  
Notasulga  
Rumsey  
Rogers  
Pleasant Grove  
Skanee  
Springerville  
Libertytown  
Church Creek  
Yellow Pine  
Dumont  
Gales Ferry  
Ravenna  
Williams  
Decatur  
Holbrook  
Sherrill  
Brownsdale  
Linden  
Sedgwick  
Fort Atkinson  
Peachtree City  
Rocheport  
West Somerset  
Clovis  
Heyburn  
Peabody  
Marion Junction  
Randall  
Hayesville  
Jordan  
White Horse Beach  
Greenville  
Macy  
Flowood  
Deep River  
Napoleon  
Leavenworth  
Coldwater  
Weldon  
Yellville  
Turners Falls  
Delray Beach  
Mineral Point  
Weldona  
Midpines  
Cascade  
Tefft  
Showell  
Bayville  
Brighton  
Grimes  
Nubieber  
North Monmouth  
Harmony  
Beaufort  
Humeston  
Baileyville  
Lakeville  
Firebrick  
Pico Rivera  
Ludington  
Channing  
West Baden Springs  
Pawnee  
Melber  
Bainbridge  
Sanders  
Dupo  
Montrose  
Schleswig  
Harbor Springs  
Richmond  
Siler  
Reeves  
Clifton  
Casco  
Crescent City  
Madisonville  
Lismore  
Panther Burn  
Hanscom Afb  
Wildie  
Mosca  
Bennington  
Lottie  
Garland  
Clutier  
Lupton  
Northfield  
Daleville  
Cuba  
Norris  
Clopton  
Renville  
Saint Paul  
Kirksville  
Kingsland  
Fairview  
Lydia  
Bridgton  
Brownstown  
Monona  
Hartland  
Lakota  
Grand Terrace  
Mesick  
Dryden  
Beverly  
Marine On Saint Croix  
Pocahontas  
Fort Meade  
Hayneville  
Yoder  
Gatewood  
Madden  
Losantville  
Cheswold  
Caseville  
Pomona  
Hopkinsville  
Jack  
Dixie  
Hillside  
Hawarden  
Cannonsburg  
North Branford  
New Liberty  
Woodstock Valley  
Farmington  
Honolulu  
Pfeifer  
Gridley  
Fulton  
Winter Park  
Monroe  
Del Mar  
Greens Fork  
Garden City  
Blue River  
New Ross  
Brilliant  
Norphlet  
Mechanic Falls  
North Middletown  
Keyes  
Neon  
Calhoun  
Mullan  
Coalgood  
Walnut  
Saint Petersburg  
Julian  
Veedersburg  
Payson  
Windom  
Ludlow  
Lindsay  
Palatka  
Bristol  
Yuma  
Zachary  
Waresboro  
Hills  
Montgomery City  
Delavan  
Magnolia  
Byron  
Dundee  
Baker  
Hyde Park  
Groveoak  
Kenner  
Many  
Berryton  
Chilhowee  
Newark  
Cowgill  
Novinger  
Goodman  
Cobalt  
South Haven  
West Hyannisport  
Jackson  
Lapeer  
Peaks Island  
Hazlehurst  
Chester  
Clarkston  
Healdsburg  
Hotchkiss  
Ravenden Springs  
Kell  
Strasburg  
Five Points  
Norris City  
Coaling  
Corcoran  
Greenway  
Woodsboro  
Strawn  
Dent  
Shingletown  
Clio  
Yalaha  
Leakesville  
Fort Lupton  
Shasta  
South Carrollton  
Taft  
Calpine  
Knobel  
Bullhead City  
Tina  
Haverhill  
Middleboro  
Siloam  
Lena  
Lee  
Freeport  
Mid Florida  
Gorham  
Bass Harbor  
Granger

#### Query #9
Weather Observation Station 10: Query the list of CITY names from STATION that do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '[^AEIOUaeiou]$';  
##### Output 
Kissee Mills  
Loma Mar  
Sandy Hook  
Tipton  
Arlington  
Turner  
Slidell  
Negreet  
Chignik Lagoon  
Hanna City  
Albany  
Monument  
Manchester  
Prescott  
Graettinger  
Sturgis  
Highwood  
Bowdon  
Tyler  
Watkins  
Republic  
Bowdon Junction  
Hoskinston  
Talbert  
Mccomb  
Kirk  
Carlock  
Seward  
Roy  
Pattonsburg  
Centertown  
Norvell  
Beaver Island  
Odin  
Jemison  
West Hills  
Culdesac  
Roselawn  
Forest Lakes  
San Simeon  
Little Rock  
Portland  
New Century  
Hampden  
Pine City  
Sandborn  
Seaton  
Prince Frederick  
Pomona Park  
Yazoo City  
Jolon  
Childs  
Shreveport  
Forest  
Sizerock  
Buffalo Creek  
Algonac  
Onaway  
Irvington  
Winsted  
Woodbury  
Hackleburg  
Soldier  
Arrowsmith  
Columbus  
Kirkland  
Wilton  
Busby  
Reeds  
Hayfork  
Mcbrides  
Lee Center  
Henderson  
Udall  
Palm Desert  
Benedict  
Oakfield  
Tamms  
Haubstadt  
Clancy  
Scotts Valley  
Norwood  
Elkton  
Bridgeport  
Cherry  
Griffin  
Pine Bluff  
Baldwin  
Pony  
Franklin  
Vulcan  
Prairie Du Rocher  
Alanson  
Carver  
Paron  
Winchester  
Greenview  
Lucerne Valley  
Cromwell  
Quinter  
Whitewater  
Round Pond  
Rockton  
Auburn  
North Berwick  
Richland  
Fremont  
Philipsburg  
Kensett  
Koleen  
Winslow  
Reasnor  
Frankfort Heights  
Linthicum Heights  
Pengilly  
Newton Center  
Newbury  
Kismet  
Canton  
Clipper Mills  
Pierre Part  
Bison  
Ridgway  
South Britain  
Rydal  
Deerfield  
Montreal  
Knob Lick  
Cranks  
Rives Junction  
Ledyard  
Norway  
Eros  
Rantoul  
Richmond Hill  
Fredericktown  
Glen Carbon  
Fredericksburg  
Mc Henry  
Wellington  
Hoffman Estates  
Edgewater  
Ducor  
Salem  
Sturdivant  
East Haddam  
Larkspur  
Patriot  
Carlos  
Addison  
Climax  
Southport  
Compton  
Rumsey  
Rogers  
Everton  
Libertytown  
Church Creek  
Dumont  
Gales Ferry  
Williams  
Decatur  
Holbrook  
Sherrill  
Linden  
Sedgwick  
Fort Atkinson  
Peachtree City  
Rocheport  
West Somerset  
Clovis  
Heyburn  
Peabody  
Marion Junction  
Randall  
Jordan  
White Horse Beach  
Macy  
Flowood  
Deep River  
Napoleon  
Leavenworth  
Coldwater  
Weldon  
Turners Falls  
Delray Beach  
Eustis  
Mineral Point  
Midpines  
Tefft  
Showell  
Brighton  
Grimes  
Nubieber  
North Monmouth  
Harmony  
Beaufort  
Union Star  
Humeston  
Firebrick  
Ludington  
Channing  
West Baden Springs  
Melber  
Sanders  
Ottertail  
Schleswig  
Harbor Springs  
Richmond  
Siler  
Reeves  
Clifton  
Crescent City  
Albion  
Athens  
Panther Burn  
Hanscom Afb  
Bennington  
Garland  
Clutier  
Lupton  
Northfield  
Osage City  
Norris  
Clopton  
Saint Paul  
Kingsland  
Fairview  
Bridgton  
Brownstown  
Hartland  
Andover  
Mesick  
Dryden  
Beverly  
Marine On Saint Croix  
Pocahontas  
Yoder  
Gatewood  
Madden  
Cheswold  
Jack  
Hawarden  
Cannonsburg  
North Branford  
New Liberty  
Woodstock Valley  
Farmington  
Pfeifer  
Gridley  
Fulton  
Winter Park  
Del Mar  
Greens Fork  
Garden City  
Blue River  
New Ross  
Brilliant  
Olmitz  
Allerton  
Norphlet  
Mechanic Falls  
North Middletown  
Keyes  
Equality  
Neon  
Calhoun  
Mullan  
Coalgood  
Walnut  
Saint Petersburg  
Julian  
Veedersburg  
Orange Park  
Payson  
Windom  
Ludlow  
Lindsay  
Bristol  
Ukiah  
Zachary  
Esmond  
Hills  
Montgomery City  
Delavan  
Byron  
Eureka Springs  
Baker  
Hyde Park  
Groveoak  
Kenner  
Many  
Berryton  
Newark  
Cowgill  
Novinger  
Goodman  
Cobalt  
South Haven  
West Hyannisport  
Jackson  
Lapeer  
Peaks Island  
Hazlehurst  
Chester  
Clarkston  
Healdsburg  
Hotchkiss  
Ravenden Springs  
Kell  
Strasburg  
Five Points  
Norris City  
Coaling  
Orange City  
Effingham  
Corcoran  
Alton  
Greenway  
Strawn  
Dent  
Shingletown  
Fort Lupton  
Agency  
South Carrollton  
Taft  
Knobel  
Bullhead City  
Anthony  
Emmett  
Haverhill  
Siloam  
Freeport  
Gorham  
Bass Harbor  
Granger

#### Query #10
Weather Observation Station 11: Query the list of CITY names from STATION that either do not start with vowels or do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '^[^AEIOUaeiou]' OR CITY RLIKE '[^AEIOUaeiou]$';   
##### Output 
Kissee Mills  
Loma Mar  
Sandy Hook  
Tipton  
Arlington  
Turner  
Slidell  
Negreet  
Glencoe  
Chelsea  
Chignik Lagoon  
Pelahatchie  
Hanna City  
Dorrance  
Albany  
Monument  
Manchester  
Prescott  
Graettinger  
Cahone  
Sturgis  
Highwood  
Waipahu  
Bowdon  
Tyler  
Watkins  
Republic  
Millville  
Bowdon Junction  
Morenci  
South El Monte  
Hoskinston  
Talbert  
Mccomb  
Kirk  
Carlock  
Seward  
Gustine  
Delano  
Westphalia  
Saint Elmo  
Roy  
Pattonsburg  
Centertown  
Norvell  
Raymondville  
Beaver Island  
Odin  
Jemison  
West Hills  
Barrigada  
Hesperia  
Wickliffe  
Culdesac  
Roselawn  
Forest Lakes  
San Simeon  
Little Rock  
Portland  
New Century  
Hampden  
Pine City  
Sandborn  
Seaton  
Milledgeville  
Prince Frederick  
Pomona Park  
Gretna  
Yazoo City  
Zionsville  
Rio Oso  
Jolon  
Childs  
Shreveport  
Forest  
Sizerock  
Buffalo Creek  
Algonac  
Onaway  
Irvington  
Winsted  
Woodbury  
Samantha  
Hackleburg  
Soldier  
Arrowsmith  
Columbus  
Bentonville  
Kirkland  
Grosse Pointe  
Wilton  
Busby  
Robertsdale  
Dale  
Reeds  
Hayfork  
Mcbrides  
Lee Center  
Tennessee  
Henderson  
Udall  
Palm Desert  
Benedict  
Oakfield  
Tamms  
Haubstadt  
Chokio  
Clancy  
Scotts Valley  
Norwood  
Elkton  
Bertha  
Bridgeport  
Cherry  
Regina  
Griffin  
Pine Bluff  
Mascotte  
Baldwin  
Netawaka  
Pony  
Franklin  
Vulcan  
Prairie Du Rocher  
Alanson  
Delta  
Carver  
Paron  
Winchester  
Jerome  
Baton Rouge  
Greenview  
Lucerne Valley  
Cromwell  
Quinter  
Whitewater  
Round Pond  
Clarkdale  
Rockton  
Pheba  
Auburn  
North Berwick  
Grandville  
Susanville  
Rosie  
Verona  
Richland  
Fremont  
Philipsburg  
Kensett  
De Tour Village  
Koleen  
Winslow  
Reasnor  
West Grove  
Frankfort Heights  
Bono  
Biggsville  
Linthicum Heights  
Marysville  
Cape Girardeau  
Pengilly  
Newton Center  
Crane Lake  
Newbury  
Kismet  
Canton  
Clipper Mills  
Grayslake  
Pierre Part  
Bison  
Bellevue  
Ridgway  
South Britain  
Rydal  
Lynnville  
Deerfield  
Montreal  
Hope  
Gowrie  
Knob Lick  
Crouseville  
Cranks  
Rives Junction  
Ledyard  
Norway  
Eros  
Rantoul  
Richmond Hill  
Fredericktown  
Glen Carbon  
Fredericksburg  
Mc Henry  
Wellington  
Hoffman Estates  
Howard Lake  
Edgewater  
Ducor  
Salem  
Sturdivant  
Hagatna  
East Haddam  
Larkspur  
Patriot  
Corriganville  
Carlos  
Addison  
Tarzana  
Grapevine  
Kanorado  
Climax  
Curdsville  
Southport  
Compton  
Notasulga  
Rumsey  
Rogers  
Pleasant Grove  
Everton  
Skanee  
Springerville  
Libertytown  
Church Creek  
Yellow Pine  
Dumont  
Gales Ferry  
Ravenna  
Williams  
Decatur  
Holbrook  
Sherrill  
Brownsdale  
Linden  
Sedgwick  
Fort Atkinson  
Peachtree City  
Rocheport  
West Somerset  
Clovis  
Heyburn  
Peabody  
Marion Junction  
Randall  
Hayesville  
Jordan  
White Horse Beach  
Greenville  
Macy  
Flowood  
Deep River  
Napoleon  
Leavenworth  
Coldwater  
Weldon  
Yellville  
Turners Falls  
Delray Beach  
Eustis  
Mineral Point  
Weldona  
Midpines  
Cascade  
Tefft  
Showell  
Bayville  
Brighton  
Grimes  
Nubieber  
North Monmouth  
Harmony  
Beaufort  
Union Star  
Humeston  
Baileyville  
Lakeville  
Firebrick  
Pico Rivera  
Ludington  
Channing  
West Baden Springs  
Pawnee  
Melber  
Bainbridge  
Sanders  
Ottertail  
Dupo  
Montrose  
Schleswig  
Harbor Springs  
Richmond  
Siler  
Reeves  
Clifton  
Casco  
Crescent City  
Madisonville  
Albion  
Lismore  
Athens  
Panther Burn  
Hanscom Afb  
Wildie  
Mosca  
Bennington  
Lottie  
Garland  
Clutier  
Lupton  
Northfield  
Daleville  
Osage City  
Cuba  
Norris  
Clopton  
Renville  
Saint Paul  
Kirksville  
Kingsland  
Fairview  
Lydia  
Bridgton  
Brownstown  
Monona  
Hartland  
Andover  
Lakota  
Grand Terrace  
Mesick  
Dryden  
Beverly  
Marine On Saint Croix  
Pocahontas  
Fort Meade  
Hayneville  
Yoder  
Gatewood  
Madden  
Losantville  
Cheswold  
Caseville  
Pomona  
Hopkinsville  
Jack  
Dixie  
Hillside  
Hawarden  
Cannonsburg  
North Branford  
New Liberty  
Woodstock Valley  
Farmington  
Honolulu  
Pfeifer  
Gridley  
Fulton  
Winter Park  
Monroe  
Del Mar  
Greens Fork  
Garden City  
Blue River  
New Ross  
Brilliant  
Olmitz  
Allerton  
Norphlet  
Mechanic Falls  
North Middletown  
Keyes  
Equality  
Neon  
Calhoun  
Mullan  
Coalgood  
Walnut  
Saint Petersburg  
Julian  
Veedersburg  
Orange Park  
Payson  
Windom  
Ludlow  
Lindsay  
Palatka  
Bristol  
Ukiah  
Yuma  
Zachary  
Esmond  
Waresboro  
Hills  
Montgomery City  
Delavan  
Magnolia  
Byron  
Dundee  
Eureka Springs  
Baker  
Hyde Park  
Groveoak  
Kenner  
Many  
Berryton  
Chilhowee  
Newark  
Cowgill  
Novinger  
Goodman  
Cobalt  
South Haven  
West Hyannisport  
Jackson  
Lapeer  
Peaks Island  
Hazlehurst  
Chester  
Clarkston  
Healdsburg  
Hotchkiss  
Ravenden Springs  
Kell  
Strasburg  
Five Points  
Norris City  
Coaling  
Orange City  
Effingham  
Corcoran  
Alton  
Greenway  
Woodsboro  
Strawn  
Dent  
Shingletown  
Clio  
Yalaha  
Leakesville  
Fort Lupton  
Shasta  
Agency  
South Carrollton  
Taft  
Calpine  
Knobel  
Bullhead City  
Tina  
Anthony  
Emmett  
Haverhill  
Middleboro  
Siloam  
Lena  
Lee  
Freeport  
Mid Florida  
Gorham  
Bass Harbor  
Granger

#### Query #11
Weather Observation Station 12: Query the list of CITY names from STATION that do not start with vowels and do not end with vowels. Your result cannot contain duplicates. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT DISTINCT CITY  
FROM STATION  
WHERE CITY RLIKE '^[^AEIOUaeiou]' AND CITY RLIKE '[^AEIOUaeiou]$';  
##### Output 
Kissee Mills  
Loma Mar  
Sandy Hook  
Tipton  
Turner  
Slidell  
Negreet  
Chignik Lagoon  
Hanna City  
Monument  
Manchester  
Prescott  
Graettinger  
Sturgis  
Highwood  
Bowdon  
Tyler  
Watkins  
Republic  
Bowdon Junction  
Hoskinston  
Talbert  
Mccomb  
Kirk  
Carlock  
Seward  
Roy  
Pattonsburg  
Centertown  
Norvell  
Beaver Island  
Jemison  
West Hills  
Culdesac  
Roselawn  
Forest Lakes  
San Simeon  
Little Rock  
Portland  
New Century  
Hampden  
Pine City  
Sandborn  
Seaton  
Prince Frederick  
Pomona Park  
Yazoo City  
Jolon  
Childs  
Shreveport  
Forest  
Sizerock  
Buffalo Creek  
Winsted  
Woodbury  
Hackleburg  
Soldier  
Columbus  
Kirkland  
Wilton  
Busby  
Reeds  
Hayfork  
Mcbrides  
Lee Center  
Henderson  
Palm Desert  
Benedict  
Tamms  
Haubstadt  
Clancy  
Scotts Valley  
Norwood  
Bridgeport  
Cherry  
Griffin  
Pine Bluff  
Baldwin  
Pony  
Franklin  
Vulcan  
Prairie Du Rocher  
Carver  
Paron  
Winchester  
Greenview  
Lucerne Valley  
Cromwell  
Quinter  
Whitewater  
Round Pond  
Rockton  
North Berwick  
Richland  
Fremont  
Philipsburg  
Kensett  
Koleen  
Winslow  
Reasnor  
Frankfort Heights  
Linthicum Heights  
Pengilly  
Newton Center  
Newbury  
Kismet  
Canton  
Clipper Mills  
Pierre Part  
Bison  
Ridgway  
South Britain  
Rydal  
Deerfield  
Montreal  
Knob Lick  
Cranks  
Rives Junction  
Ledyard  
Norway  
Rantoul  
Richmond Hill  
Fredericktown  
Glen Carbon  
Fredericksburg  
Mc Henry  
Wellington  
Hoffman Estates  
Ducor  
Salem  
Sturdivant  
Larkspur  
Patriot  
Carlos  
Climax  
Southport  
Compton  
Rumsey  
Rogers  
Libertytown  
Church Creek  
Dumont  
Gales Ferry  
Williams  
Decatur  
Holbrook  
Sherrill  
Linden  
Sedgwick  
Fort Atkinson  
Peachtree City  
Rocheport  
West Somerset  
Clovis  
Heyburn  
Peabody  
Marion Junction  
Randall  
Jordan  
White Horse Beach  
Macy  
Flowood  
Deep River  
Napoleon  
Leavenworth  
Coldwater  
Weldon  
Turners Falls  
Delray Beach  
Mineral Point  
Midpines  
Tefft  
Showell  
Brighton  
Grimes  
Nubieber  
North Monmouth  
Harmony  
Beaufort  
Humeston  
Firebrick  
Ludington  
Channing  
West Baden Springs  
Melber  
Sanders  
Schleswig  
Harbor Springs  
Richmond  
Siler  
Reeves  
Clifton  
Crescent City  
Panther Burn  
Hanscom Afb  
Bennington  
Garland  
Clutier  
Lupton  
Northfield  
Norris  
Clopton  
Saint Paul  
Kingsland  
Fairview  
Bridgton  
Brownstown  
Hartland  
Mesick  
Dryden  
Beverly  
Marine On Saint Croix  
Pocahontas  
Yoder  
Gatewood  
Madden  
Cheswold  
Jack  
Hawarden  
Cannonsburg  
North Branford  
New Liberty  
Woodstock Valley  
Farmington  
Pfeifer  
Gridley  
Fulton  
Winter Park  
Del Mar  
Greens Fork  
Garden City  
Blue River  
New Ross  
Brilliant  
Norphlet  
Mechanic Falls  
North Middletown  
Keyes  
Neon  
Calhoun  
Mullan  
Coalgood  
Walnut  
Saint Petersburg  
Julian  
Veedersburg  
Payson  
Windom  
Ludlow  
Lindsay  
Bristol  
Zachary  
Hills  
Montgomery City  
Delavan  
Byron  
Baker  
Hyde Park  
Groveoak  
Kenner  
Many  
Berryton  
Newark  
Cowgill  
Novinger  
Goodman  
Cobalt  
South Haven  
West Hyannisport  
Jackson  
Lapeer  
Peaks Island  
Hazlehurst  
Chester  
Clarkston  
Healdsburg  
Hotchkiss  
Ravenden Springs  
Kell  
Strasburg  
Five Points  
Norris City  
Coaling  
Corcoran  
Greenway  
Strawn  
Dent  
Shingletown  
Fort Lupton  
South Carrollton  
Taft  
Knobel  
Bullhead City  
Haverhill  
Siloam  
Freeport  
Gorham  
Bass Harbor  
Granger

## Problem Set Table #3

The STUDENTS table is described as follows:
<img src='images/1443815243-94b941f556-1.jpg'>
The Name column only contains uppercase (A-Z) and lowercase (a-z) letters.

### Problems
1. Higher Than 75 Marks: Query the Name of any student in STUDENTS who scored higher than 75 Marks. Order your output by the last three characters of each name. If two or more students both have names ending in the same last three characters (i.e.: Bobby, Robby, etc.), secondary sort them by ascending ID. (Difficulty: <span style='color:green'>Easy</span>)

#### Query #1
Higher Than 75 Marks: Query the Name of any student in STUDENTS who scored higher than 75 Marks. Order your output by the last three characters of each name. If two or more students both have names ending in the same last three characters (i.e.: Bobby, Robby, etc.), secondary sort them by ascending ID. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT NAME  
FROM STUDENTS  
WHERE MARKS > 75  
ORDER BY RIGHT(NAME, 3) ASC, ID ASC;  
##### Output 
Stuart  
Kristeen  
Christene  
Amina  
Aamina  
Priya  
Heraldo  
Scarlet  
Julia  
Salma  
Britney  
Priyanka  
Samantha  
Vivek  
Belvet  
Devil  
Evil

## Problem Set Table #4

The Employee table containing employee data for a company is described as follows:
<img src='images/1458557872-4396838885-ScreenShot2016-03-21at4.27.13PM.png'>
where employee_id is an employee's ID number, name is their name, months is the total number of months they've been working for the company, and salary is their monthly salary.

### Problems
1. Employee Names: Write a query that prints a list of employee names (i.e.: the name attribute) from the Employee table in alphabetical order. (Difficulty: <span style='color:green'>Easy</span>)
2. Employee Salaries: Write a query that prints a list of employee names (i.e.: the name attribute) for employees in Employee having a salary greater than $2000 per month who have been employees for less than 10 months. Sort your result by ascending employee_id. (Difficulty: <span style='color:green'>Easy</span>)

#### Query #1
Employee Names: Write a query that prints a list of employee names (i.e.: the name attribute) from the Employee table in alphabetical order. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT name  
FROM Employee  
ORDER BY name ASC;  
##### Output 
Alan  
Amy  
Andrew  
Andrew  
Angela  
Ann  
Anna  
Anthony  
Antonio  
Benjamin  
Bonnie  
Brandon  
Brandon  
Brian  
Carol  
Charles  
Christina  
Christina  
Christine  
Christine  
David  
David  
David  
Debra  
Diana  
Diana  
Donna  
Dorothy  
Dorothy  
Dorothy  
Earl  
Elizabeth  
Emily  
Evelyn  
Evelyn  
Frank  
Gerald  
Gloria  
Gregory  
Harry  
Jacqueline  
James  
James  
Jean  
Jennifer  
Jesse  
Jesse  
Joe  
Joe  
John  
John  
Jonathan  
Joseph  
Joyce  
Joyce  
Julia  
Keith  
Kelly  
Kevin  
Kimberly  
Kimberly  
Lawrence  
Lillian  
Linda  
Lisa  
Lori  
Louise  
Maria  
Marilyn  
Marilyn  
Marilyn  
Martha  
Martin  
Matthew  
Melissa  
Michael  
Michelle  
Nancy  
Norma  
Pamela  
Patricia  
Patrick  
Paul  
Paul  
Paula  
Paula  
Phillip  
Ralph  
Robert  
Robin  
Robin  
Rose  
Roy  
Stephanie  
Tammy  
Timothy  
Todd  
Victor  
Walter  
Willie

#### Query #2
Employee Salaries: Write a query that prints a list of employee names (i.e.: the name attribute) for employees in Employee having a salary greater than $2000 per month who have been employees for less than 10 months. Sort your result by ascending employee_id. (Difficulty: <span style='color:green'>Easy</span>)
##### Query 
SELECT name  
FROM Employee  
WHERE salary > 2000 AND months < 10  
ORDER BY employee_id ASC;  
##### Output 
Rose  
Patrick  
Lisa  
Amy  
Pamela  
Jennifer  
Julia  
Kevin  
Paul  
Donna  
Michelle  
Christina  
Brandon  
Joseph  
Jesse  
Paula  
Louise  
Evelyn  
Emily  
Jonathan  
Nancy  
Benjamin  
Roy  
Diana  
Christine